[package]
name = "waysmoke-shell"
version = "2020.5.0"
authors = ["Val Packett <val@packett.cool>"]
edition = "2018"

[dependencies]
futures = "0.3"
glib = "0.9"
gio = "0.8"
linicon = "0.4"

wstk = { path = "../wstk" }
